kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-deploy
spec:
  selector:
    matchLabels:
      app: rs
  replicas: 2
  template:
    metadata:
      name: test-pod
      labels:
        app: rs
    spec:
      containers:
       - name: version1
         image: nginx
         ports:
           - containerPort: 80

---
kind: Service
apiVersion: v1
metadata: 
  name: test-ser
spec:
  selector:
    app: rs
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deploy
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40